"use client";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import { ThemeProvider, CssBaseline, Box } from "@mui/material";
import theme from "../../theme";
import BottomNav from "@/components/bottomNavigation";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {isClient && <Navbar />}
          <Box
            component="main"
            sx={{
              paddingBottom: "50px",
              minHeight: "100vh",
            }}
          >
            {children}
          </Box>
          {isClient && <BottomNav />}
        </ThemeProvider>
      </body>
    </html>
  );
}
